### ISSUE TITLE
Getting Auto Logout

### ISSUE THREAD

**Issue by JBavaliya** [cortezaproject/corteza-vue#40]
Hii

I'm using ` "@cortezaproject/corteza-vue": "^2021.3.x"` in my project and getting token form `auth/oauth2/default-client` request data with refresh token

I'm gettting redirecting on autlo logout after 2 hrs so how itt can prevant it , do i need to create new token from refresh token and how and when i need to create this new token

**Comment by darh** [comment]
Sessions expire after 1 hour (default). 

Do you get any errors? Does this happen even if you keep one of the webapps open? It should not - webapps send refresh tokens and auto extend the session.
