### ISSUE TITLE
impersonate Issues 

### ISSUE THREAD

**Issue by JBavaliya** [cortezaproject/corteza-vue#52]
I have one user and admin. when i am trying to login with imponate with admin username pass it's returning error with blow response.

i am using below function for imposonate with paramter `({ userID: userID })`. User have alreay administetor permission.

```
authImpersonate(a: KV): Promise<KV>;
```

Response ::
```
{
    "error": "not allowed to impersonate this user"
}
```

**Comment by zmija** [comment]
Hello @JBavaliya, and welcome to Corteza!

The error message suggests something is off with permissions (the user trying to impersonate doesn't have a right to do so).

Can I kindly ask you to try to impersonate with a super admin to validate this?

**Comment by jitendraflowz03** [comment]
@zmija 

Thanks, now it's working

**Comment by darh** [comment]
Closed to inactivity.
