### ISSUE TITLE
This request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by paradoxe35** [cortezaproject/corteza-vue#82]
The page at 'https://domain.com/auth/callback?code=**&state=**' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domain.com/auth/oauth2/default-client'. This request has been blocked; the content must be served over HTTPS.

**Comment by darh** [comment]
Repository moved and archived.

If problem is still there please open an issue on https://github.com/cortezaproject/corteza
